CreateSftpSettings:
  type: object
  required:
    - host
    - port
    - username
    - private_key
    - root_path
  properties:
    host:
      type: string
    port:
      type: number
    username:
      type: string
    private_key:
      type: string
    passphrase:
      type: string
    root_path:
      type: string
  example:
    host: '1.1.1.1'
    port: 22
    username: john
    private_key: '-----BEGIN RSA PRIVATE KEY-----\n0ndjOb0Vb0TPtj8rRrGcvnbINEyRK6aC1HxUIgSaZAizAbtTYJ+GH06LJKyoD8T4\n-----END RSA PRIVATE KEY-----'
    passphrase: 'secret'
    root_path: '/root/'
