---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{ include "common.labels" . | indent 4 }}
  name: pdf-generate-api-{{ .Release.Namespace }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent_volume.size }}
---