---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecretName }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pdf-generate-service-{{ .Release.Namespace }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
data:
  LARAVEL_DB_PASSWORD: {{ required "DB Password for pdf generate service is required" .Values.laravel_db_password | b64enc }}
  LARAVEL_PERSONAL_ACCESS_CLIENT_ID: {{ required "Laravel Personal Access Client Id for pdf generate service is required" .Values.laravel_personal_access_client_id | b64enc }}
  LARAVEL_HORIZON_BASIC_AUTH_USERNAME: {{ required "Laravel Horizon Basic Auth Username for pdf generate service  is required" .Values.laravel_horizon_basic_auth_username | b64enc }}
  LARAVEL_HORIZON_BASIC_AUTH_PASSWORD: {{ required "Laravel Horizon Basic Auth Password  for pdf generate service is required" .Values.laravel_horizon_basic_auth_password | b64enc }}
  OAUTH_PRIVATE_KEY: {{ required "Oauth private key for pdf genrate service is required" .Values.oauth_private_key | b64enc }}
  OAUTH_PUBLIC_KEY: {{ required "Oauth public key for pdf genrate service is required" .Values.oauth_public_key | b64enc }}
---
