apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-{{ .Release.Namespace }}-svc
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pdf-generate-service
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9100
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}